# Generated by Django 5.1.1 on 2024-10-07 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_subscription'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscription',
            old_name='monthly_price',
            new_name='monthlyPrice',
        ),
        migrations.RenameField(
            model_name='subscription',
            old_name='yearly_price',
            new_name='yearlyPrice',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='Company',
            new_name='company',
        ),
        migrations.AddField(
            model_name='user',
            name='postAddress',
            field=models.TextField(null=True),
        ),
    ]
