# Generated by Django 5.1.1 on 2024-10-08 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_rename_monthly_price_subscription_monthlyprice_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscription',
            old_name='name',
            new_name='package',
        ),
        migrations.RemoveField(
            model_name='user',
            name='postAddress',
        ),
    ]
